### ISSUE TITLE
[SP] Sysid/Speed control of rear wheel motors

### ISSUE THREAD

**Issue by alezana** [idsc-frazzoli/retina#230]
> Until mid-April 2018, the speed of the gokart was controlled by a PI-controller. That controller proved unreliable to make the gokart reach zero velocity, i.e. come to a halt. Instead, the vehicle would drive reverse. Since then, we downgraded to a P-controller.

> We have conducted experiments that input synthetic signals of various amplitudes to the motors: PRBS, Chirp, etc. During the experiments, a safety driver was seated inside the gokart and the steering was straight.

The task is to develop a fast and robust speed controller for the gokart that outperforms the current P-controller.

Related document: [20180617_rimo_response.pdf](https://github.com/idsc-frazzoli/retina/files/2109415/20180617_rimo_response.pdf)

**Comment by datahaki** [comment]
[20180617_rimo_response.pdf](https://github.com/idsc-frazzoli/retina/files/2109415/20180617_rimo_response.pdf)

**Comment by alezana** [comment]
#408
