### ISSUE TITLE
DAVIS240C data

### ISSUE THREAD

**Issue by xueyinhualuo** [idsc-frazzoli/retina#654]
Hello,  thank you for your code. Can you share the DAVIS240C data (like the cat and the pedestrian scenes)?

**Comment by datahaki** [comment]
here is a sample lcm log file
https://polybox.ethz.ch/index.php/s/noefnDZ1eiv75vo
that you can play back live using `GokartLcmLogPlayer`.
Simultaneously launch the module `DavisDetailModule` to show the Davis240C events as the log player plays back the file.

**Comment by xueyinhualuo** [comment]
Thanks for your kindly help. I'm sorry to bother you. Can you share the data in AEDAT format? I want to use the data in other projects (e.g., event-based object tracking).
